/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEyeglassesRouteImport } from './routes/_authenticated/eyeglasses'
import { Route as AuthenticatedDrawersRouteImport } from './routes/_authenticated/drawers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as preAuthRegisterRouteImport } from './routes/(preAuth)/register'
import { Route as preAuthLoginRouteImport } from './routes/(preAuth)/login'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEyeglassesRoute = AuthenticatedEyeglassesRouteImport.update({
  id: '/eyeglasses',
  path: '/eyeglasses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDrawersRoute = AuthenticatedDrawersRouteImport.update({
  id: '/drawers',
  path: '/drawers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const preAuthRegisterRoute = preAuthRegisterRouteImport.update({
  id: '/(preAuth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const preAuthLoginRoute = preAuthLoginRouteImport.update({
  id: '/(preAuth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/login': typeof preAuthLoginRoute
  '/register': typeof preAuthRegisterRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drawers': typeof AuthenticatedDrawersRoute
  '/eyeglasses': typeof AuthenticatedEyeglassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/login': typeof preAuthLoginRoute
  '/register': typeof preAuthRegisterRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drawers': typeof AuthenticatedDrawersRoute
  '/eyeglasses': typeof AuthenticatedEyeglassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/profile': typeof ProfileRoute
  '/(preAuth)/login': typeof preAuthLoginRoute
  '/(preAuth)/register': typeof preAuthRegisterRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drawers': typeof AuthenticatedDrawersRoute
  '/_authenticated/eyeglasses': typeof AuthenticatedEyeglassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/login'
    | '/register'
    | '/brands'
    | '/companies'
    | '/dashboard'
    | '/drawers'
    | '/eyeglasses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/login'
    | '/register'
    | '/brands'
    | '/companies'
    | '/dashboard'
    | '/drawers'
    | '/eyeglasses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/profile'
    | '/(preAuth)/login'
    | '/(preAuth)/register'
    | '/_authenticated/brands'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/drawers'
    | '/_authenticated/eyeglasses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  preAuthLoginRoute: typeof preAuthLoginRoute
  preAuthRegisterRoute: typeof preAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eyeglasses': {
      id: '/_authenticated/eyeglasses'
      path: '/eyeglasses'
      fullPath: '/eyeglasses'
      preLoaderRoute: typeof AuthenticatedEyeglassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drawers': {
      id: '/_authenticated/drawers'
      path: '/drawers'
      fullPath: '/drawers'
      preLoaderRoute: typeof AuthenticatedDrawersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(preAuth)/register': {
      id: '/(preAuth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof preAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(preAuth)/login': {
      id: '/(preAuth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof preAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDrawersRoute: typeof AuthenticatedDrawersRoute
  AuthenticatedEyeglassesRoute: typeof AuthenticatedEyeglassesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDrawersRoute: AuthenticatedDrawersRoute,
  AuthenticatedEyeglassesRoute: AuthenticatedEyeglassesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ProfileRoute: ProfileRoute,
  preAuthLoginRoute: preAuthLoginRoute,
  preAuthRegisterRoute: preAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
